package agent

import (
	"github.com/vibe-mvp/internal/realize/dag"
	"github.com/vibe-mvp/internal/realize/memory"
	"github.com/vibe-mvp/internal/realize/skills"
)

// Context bundles everything an agent needs for one task invocation.
type Context struct {
	Task           *dag.Task
	SkillDocs      []skills.Doc
	PreviousErrors string // non-empty on retry attempts
	// DependencyOutputs holds the files generated by upstream tasks that this
	// task depends on. Agents use this as shared memory to stay consistent with
	// the types, schemas, and interfaces already produced by the wider team.
	DependencyOutputs []*memory.TaskOutput
}
